### ISSUE TITLE
Inmemory table dissappears after query

### ISSUE THREAD

**Issue by shagabutdinov** [jmoiron/sqlx#164]
Table dissappears from inmemory database when NamedQuery is used. I have following code:

```
package main

import (
	"log"

	"github.com/jmoiron/sqlx"
	_ "github.com/mattn/go-sqlite3"
)

type User struct {
	Id   int    `db:"id"`
	Name string `db:"name"`
}

func findUserAndLogName(connection *sqlx.DB) {
	rows, err := connection.NamedQuery(
		`SELECT id, name FROM user WHERE name = :name`,
		map[string]interface{}{"name": "TEST"},
	)

	if err != nil {
		panic(err)
	}

	if !rows.Next() {
		panic("not found")
	}

	user := User{}
	if err := rows.StructScan(&user); err != nil {
		panic(err)
	}

	log.Printf("LOG(main-sqlx.go:34) - %+v", user.Name)
}

func main() {
	connection, _ := sqlx.Connect("sqlite3", ":memory:") // connection error is ignored in example
	connection.MustExec(`
		CREATE TABLE user (id INTEGER NOT NULL PRIMARY KEY, name TEXT);
 		INSERT INTO user (id, name) VALUES (1, "TEST");
 	`)

	findUserAndLogName(connection) // output: TEST
	findUserAndLogName(connection) // panics here
}
```

The output of the "go run" is following:

```
$ go run main-sqlx.go
2015/09/02 15:02:32 LOG(main-sqlx.go:34) - TEST
panic: no such table: user

goroutine 1 [running]:
main.findUserAndLogName(0xc20803a330)
	/home/leo/src/go/src/tmp3/main-sqlx.go:22 +0x178
main.main()
	/home/leo/src/go/src/tmp3/main-sqlx.go:45 +0xab

goroutine 5 [chan receive]:
database/sql.(*DB).connectionOpener(0xc20802c000)
	/usr/lib/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
	/usr/lib/go/src/database/sql/sql.go:452 +0x31c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1
exit status 2
```

Similar program that does not use sqlx extension works fine: 

```
package main

import (
	"database/sql"
	"log"

	_ "github.com/mattn/go-sqlite3"
)

type User struct {
	Id   int    `db:"id"`
	Name string `db:"name"`
}

func findUserAndLogName(connection *sql.DB) {
	id := 0
	username := ""

	err := connection.
		QueryRow(`SELECT id, name FROM user WHERE name = ?`, "TEST").
		Scan(&id, &username)

	if err != nil {
		panic(err)
	}

	user := User{Id: id, Name: username}
	log.Printf("LOG(main-sqlx.go:125) - %+v", user.Name)
}

func main() {
	connection, _ := sql.Open("sqlite3", ":memory:") // connection error is ignored in example
	connection.Exec(`
		CREATE TABLE user (id INTEGER NOT NULL PRIMARY KEY, name TEXT);
		INSERT INTO user (id, name) VALUES (1, "TEST");
	`)

	findUserAndLogName(connection) // output: TEST
	findUserAndLogName(connection) // not panics
}
```

Output:

```
$ go run main-sql.go
2015/09/02 15:03:11 LOG(main-sqlx.go:125) - TEST
2015/09/02 15:03:11 LOG(main-sqlx.go:125) - TEST
```

Tables should be preserved in inmemory database when SELECT queries are executed.

**Comment by shagabutdinov** [comment]
Therefore cached database works fine:

```
connection, _ := sqlx.Connect("sqlite3", "file::memory:?cache=shared") // connection error is ignored in example
```

**Comment by jmoiron** [comment]
These aren't equivalent.  When I alter the vanilla `database/sql` version to use `db.Query` instead of `db.QueryRow`, it fails like the sqlx version.

**Comment by jmoiron** [comment]
You are not closing nor fully-iterating your `rows` object which means it is leaving an open connection.  If you use `db.SetMaxOpenConnections(1)` (which you should, to make this safe), you will see it hangs.  QueryRow automatically closes the underlying rows so it doesn't cause the extra connections to be made.

**Comment by jmoiron** [comment]
From the [sqlite documentation](https://www.sqlite.org/inmemorydb.html):

```When this is done, no disk file is opened. Instead, a new database is created purely in memory. The database ceases to exist as soon as the database connection is closed. Every :memory: database is distinct from every other.```

So new connection no longer has the bootstrapped table.

**Comment by shagabutdinov** [comment]
Thank you very much! I misused the sqlite3 api, and rows.Close() solved the
problem. That strange, that sqlite3 didn't return error so it was not
obvious what's going on.


--
Leonid Shagabutdinov,
+7 905 937 6988
