### ISSUE TITLE
StructScan an Array Aggregate

### ISSUE THREAD

**Issue by tgrosinger** [jmoiron/sqlx#168]
I have two tables that go something like this:

```sql
                   Table "public.shareditem"
    Column    |         Type         |          Modifiers                            
--------------+----------------------+-----------------------------
 id           | integer              | not null
 role_name    | character varying(4) | not null
 dashboard_id | integer              | 

                Table "public.dashboard"
   Column    |          Type          |          Modifiers                            
-------------+------------------------+-------------------------------
 id          | integer                | not null
 deleted     | boolean                | not null
 description | text                   | 
 name        | text                   | 
```

There are a few pieces left out, but that is the important part. Next I am using this SQL query to get some results that I want to put in a struct:

```sql
SELECT d.id, d.description, d.name, array_agg(s.role_name) as roles
FROM dashboard d JOIN shareditem s on s.dashboard_id = d.id
WHERE d.deleted is false
GROUP BY d.id
```

```go
type Dashboard struct {
    ID int64
    Description string
    Name string
    Roles []string
}

var results []Dashboard
err := db.Select(&results, query)

if err != nil {
    fmt.Println(err.Error())
} else {
    fmt.Println(results)
}
```

Maybe I am doing something wrong? Here is the error I am getting:

```
http: panic serving 127.0.0.1:39893: reflect.Set: value of type []uint8 is not assignable to type []string goroutine 21 [running]: net/http.(*conn).serve.func1(0xc8200d4580, 0x7fd6b43fdf10, 0xc82002e168) ^I/usr/lib/go/src/net/http/server.go:1287 +0xb5 reflect.Value.assignTo(0x85b1a0, 0xc8201eb4e0, 0x57, 0xa02310, 0xb, 0x854780, 0x0, 0x0, 0x0, 0x0) ^I/usr/lib/go/src/reflect/value.go:2158 +0x3be reflect.Value.Set(0x854780, 0xc82020c320, 0xd7, 0x85b1a0, 0xc8201eb4e0, 0x57) ^I/usr/lib/go/src/reflect/value.go:1327 +0x95 database/sql.convertAssign(0xc82027fa90, 0xc82020c320, 0x85b1a0, 0xc8201eb4e0, 0x0, 0x0) ^I/usr/lib/go/src/database/sql/convert.go:207 +0x7ca database/sql.(*Rows).Scan(0xc820237c20, 0xc820594480, 0x9, 0x9, 0x0, 0x0) ^I/usr/lib/go/src/database/sql/sql.go:1692 +0x47a github.com/jmoiron/sqlx.scanAll(0x7fd6b4415940, 0xc82027fa40, 0x83eac0, 0xc8201eb220, 0x0, 0x0, 0x0) ^I/depot/vendor/golibs/src/github.com/jmoiron/sqlx/sqlx.go:901 +0xc15 github.com/jmoiron/sqlx.Select(0
```

Sorry about the chopped off end. Had to pull it from the logs.
Why does it think that this value is a []uint8?

**Comment by tgrosinger** [comment]
It turns out the problem is with how `array_agg` functions. `string_agg` would have worked great, except that my column is a varchar, not a text.

Here is a solution:

1. Change the query, surrounding `array_add(s.role_name)` in an `array_to_string`.

```sql
SELECT d.id, d.description, d.name, array_to_string(array_agg(s.role_name), ',') as roles
FROM dashboard d JOIN shareditem s on s.dashboard_id = d.id
WHERE d.deleted is false
GROUP BY d.id
```

2. Change the struct being scanned into to expect a single string

```go
type Dashboard struct {
    ID int64
    Description string
    Name string
    Roles string
}
```

3. Iterate through each result, and split the string on comma. You will unfortunately need a temporary data structure or just use a different field.

**Comment by jsteenb2** [comment]
@tgrosinger you could also try something like

`STRING_TO_ARRAY(ARRAY_TO_STRING(ARRAY_AGG(s.role_name), ',,,'), ',,,')` to produce that string array without the nulls, food for thought 👍
