### ISSUE TITLE
Cannot insert specific time using Named Queries

### ISSUE THREAD

**Issue by lumenphp** [jmoiron/sqlx#545]
I would like to insert a known timestamp into MySQL. I am using time.Now() for this test. Did I miss anything obvious? Here is the table,

CREATE TABLE car (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(100) DEFAULT NULL,
  ts timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB

=============
{code}
package main

import (
        _ "database/sql"
        _ "github.com/go-sql-driver/mysql"
        "github.com/jmoiron/sqlx"
        "log"
        "time"
        "fmt"
)

type car struct {
        Id   int
        Name string
        Ts   time.Time
}

func main() {
        db, err := sqlx.Open("mysql", "xxx:xxxxx@tcp(127.0.0.1:3306)/dbname?parseTime=true&charset=utf8")

        if err != nil {
                log.Println(err)
        }

        defer db.Close()

        v := car{Id: 5, Name: "Beetle", Ts: time.Now() }

        fmt.Println(v)
        stmt, err := db.PrepareNamed(`INSERT INTO car VALUES (:id, :name, :ts)`)
        _, err = stmt.Exec(v)
}

Error:
----------------
{5 Beetle 2019-08-07 01:11:15.178503955 +0000 UTC m=+0.000601133}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x604ec6]

goroutine 1 [running]:
github.com/jmoiron/sqlx.(*NamedStmt).Exec(0x0, 0x65c980, 0xc00010a060, 0xc00010a060, 0x0, 0x6cfaa0, 0xc000112020)
	/root/go/src/github.com/jmoiron/sqlx/named.go:43 +0x26
main.main()
	/root/go/src/dbtest/sqlx_insert.go:37 +0x284
exit status 2

**Comment by lumenphp** [comment]
Sorry! ts column in DB is actually changed by a script! Everything works as it supposed to be.
