### ISSUE TITLE
RowsAffected panics when exec is successful

### ISSUE THREAD

**Issue by chuabingquan** [jmoiron/sqlx#568]
When `RowsAffected` is invoked after `db.Exec` executes a successful deletion, the program panics as shown below. However, `RowsAffected` does not panic if there are no fields being deleted. What could be the issue?

```go
result, err := db.Exec(`DELETE FROM table WHERE uuid_to_bin(?)`, tableID)
count, err := result.RowsAffected()
```

```bash
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1240f9a]

goroutine 68 [running]:
testing.tRunner.func1(0xc000174c00)
        /usr/local/go/src/testing/testing.go:830 +0x388
panic(0x128a8e0, 0x14d82c0)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
backend/mysql.(*UserService).DeleteUser(0xc0000ff9a0, 0x12d466d, 0x5, 0x5da8754c, 0x35d1d118)
        /Users/bq/Desktop/PROJECTS/code/active/p/code/backend/mysql/users.go:150 +0x10a
backend/mysql_test.TestDeleteUser.func1(0xc000174c00)
        /Users/bq/Desktop/PROJECTS/code/active/p/code/backend/mysql/users_test.go:158 +0x49
testing.tRunner(0xc000174c00, 0xc0000ffaa0)
        /usr/local/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:916 +0x357
```

**Comment by chuabingquan** [comment]
My bad, I forgot to check for errors before invoking `rowsAffected` on a nil pointer result.
