### ISSUE TITLE
Panic for NamedExec example from README

### ISSUE THREAD

**Issue by a-dot** [jmoiron/sqlx#794]
```
	db, err := sqlx.Open("sqlite3", "tcp://127.0.0.1:1234")
	if err != nil {
		panic(err)
	}

	personStructs := []Person{
		{FirstName: "Ardie", LastName: "Savea", Email: "asavea@ab.co.nz"},
		{FirstName: "Sonny Bill", LastName: "Williams", Email: "sbw@ab.co.nz"},
		{FirstName: "Ngani", LastName: "Laumape", Email: "nlaumape@ab.co.nz"},
	}

	db.NamedExec(`INSERT INTO person (first_name, last_name, email) VALUES (:first_name, :last_name, :email)`, personStructs)
```

I get this panic:

```
panic: reflect: call of github.com/jmoiron/sqlx/reflectx.(*Mapper).TraversalsByNameFunc on slice Value

goroutine 1 [running]:
github.com/jmoiron/sqlx/reflectx.mustBe({0x57868f8, 0x43bc940}, 0x19)
	/Users/a-dot/go/pkg/mod/github.com/jmoiron/sqlx@v1.2.0/reflectx/reflect.go:249 +0x97
github.com/jmoiron/sqlx/reflectx.(*Mapper).TraversalsByNameFunc(0x43bc940, {0x44824b0, 0x43bc940}, {0xc000114500, 0x3, 0x60}, 0xc000121da0)
	/Users/a-dot/go/pkg/mod/github.com/jmoiron/sqlx@v1.2.0/reflectx/reflect.go:187 +0x6f
github.com/jmoiron/sqlx.bindArgs({0xc000114500, 0x3, 0xa}, {0x43bc940, 0xc00000e228}, 0x1000000040dd445)
	/Users/a-dot/go/pkg/mod/github.com/jmoiron/sqlx@v1.2.0/named.go:166 +0x2be
github.com/jmoiron/sqlx.bindStruct(0x10000000400ea67, {0x44289a5, 0x8}, {0x43bc940, 0xc00000e228}, 0x18)
	/Users/a-dot/go/pkg/mod/github.com/jmoiron/sqlx@v1.2.0/named.go:203 +0x85
github.com/jmoiron/sqlx.bindNamedMapper(0x4412d20, {0x44289a5, 0xc000121ef8}, {0x43bc940, 0xc00000e228}, 0x43ca720)
	/Users/a-dot/go/pkg/mod/github.com/jmoiron/sqlx@v1.2.0/named.go:333 +0x46
github.com/jmoiron/sqlx.NamedExec({0x447e6c0, 0xc00007e9c0}, {0x44289a5, 0x5a}, {0x43bc940, 0xc00000e228})
	/Users/a-dot/go/pkg/mod/github.com/jmoiron/sqlx@v1.2.0/named.go:351 +0x1f5
github.com/jmoiron/sqlx.(*DB).NamedExec(...)
	/Users/a-dot/go/pkg/mod/github.com/jmoiron/sqlx@v1.2.0/sqlx.go:315
```

**Comment by hasheddan** [comment]
@a-dot I hit this as well, looks like bumping to a newer version provides the fix https://github.com/jmoiron/sqlx/issues/519#issuecomment-704060007
