### ISSUE TITLE
Big error in mysql version 8.0.31

### ISSUE THREAD

**Issue by chlinwei** [jmoiron/sqlx#840]
This is my simple code to create two tables,I run it in centos7 or windows 10 ,It'll show the below error.
If I just create one of the two table ,It can work fine. But If I  create two table ,It'll will run error.
I use the mysql command to execute this sql ,It works fine. Now I am very confused.

```
package main 
import (
	"log"
	_ "github.com/go-sql-driver/mysql"
	"github.com/jmoiron/sqlx"
)

func main() {
	d, err := sqlx.Connect("mysql", "monitor:Password111@(192.168.201.210:3306)/monitor")
	if err != nil {
		log.Fatalln("db connect error:%s", err.Error())
		panic(err)
	}
	d.SetConnMaxIdleTime(10)
	d.SetMaxOpenConns(30)
	var schema = `
	CREATE TABLE IF NOT EXISTS AlertGroup (
	ID INT NOT NULL AUTO_INCREMENT,
	time TIMESTAMP NOT NULL,
	receiver VARCHAR(100) NOT NULL,
	status VARCHAR(50) NOT NULL,
	externalURL TEXT NOT NULL,
	groupKey VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

	CREATE TABLE IF NOT EXISTS GroupLabel (
		ID INT NOT NULL AUTO_INCREMENT,
		AlertGroupID INT NOT NULL,
		GroupLabel VARCHAR ( 100 ) NOT NULL,
		VALUE VARCHAR ( 1000 ) NOT NULL,
		PRIMARY KEY ( ID )) ENGINE = INNODB DEFAULT CHARSET = utf8;
		`
	d.MustExec(schema)

}
```

panic: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE IF NOT EXISTS GroupLabel (
                ID INT NOT NULL AUTO_INCREMENT,
                Aler' at line 11

goroutine 1 [running]:
github.com/jmoiron/sqlx.MustExec(...)
        C:/Users/cn200037790/go/pkg/mod/github.com/jmoiron/sqlx@v1.3.5/sqlx.go:722
github.com/jmoiron/sqlx.(*DB).MustExec(0xc000022c30?, {0xb3eb73?, 0xb3c739?}, {0x0?, 0xc000044000?, 0xc000115f70?})
        C:/Users/cn200037790/go/pkg/mod/github.com/jmoiron/sqlx@v1.3.5/sqlx.go:366 +0x46
main.main()
        D:/workspace/go/test/test1/main.go:35 +0x85

**Comment by chlinwei** [comment]
sorry , I use the primitive sql to do this, I also get the same error.

**Comment by Holyson** [comment]
debug usually execute the primitive sql,second search the code bug
