### ISSUE TITLE
mysql connect error

### ISSUE THREAD

**Issue by zigaai** [jmoiron/sqlx#896]
i use sea-orm to connect mysql, it cannot connet. but when i use other client, its work
mysql_version: 5.7.23-log
url: mysql://root:123456@172.16.90.27:31295/demo

sqlx version: 0.7.2
sea-orm version: 0.12.3

error stack:
```tex
thread 'main' panicked at 'connect database error!: Conn(SqlxError(Tls(Os { code: -2146893018, kind: Uncategorized, message: "接收到的消息异常，或格式不正确。" })))', src\config\db.rs:44:41
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\std\src\panicking.rs:593
   1: core::panicking::panic_fmt
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\core\src\panicking.rs:67
   2: core::result::unwrap_failed
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\core\src\result.rs:1651
   3: enum2$<core::result::Result<enum2$<sea_orm::database::db_connection::DatabaseConnection>,enum2$<sea_orm::error::DbErr> > >::expect<enum2$<sea_orm::database::db_connection::DatabaseConnection>,enum2$<sea_orm::error::DbErr> >
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26\library\core\src\result.rs:1033
   4: simple_code_gen::config::db::init::async_fn$0
             at .\src\config\db.rs:44
   5: simple_code_gen::config::init::async_fn$0
             at .\src\config\mod.rs:36
   6: simple_code_gen::main::async_block$0
             at .\src\main.rs:15
```

rust:
```tex
$ cargo -V
cargo 1.71.1 (7f1d04c00 2023-07-29)
$ rustup -V
rustup 1.26.0 (5af9b9484 2023-04-05)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.71.1 (eb26296b5 2023-08-03)`
```

other client connect status:
![image](https://github.com/jmoiron/sqlx/assets/50167241/f3addc05-b9d9-4ee7-87dd-696f8678acc1)

**Comment by mohammed90** [comment]
Wrong sqlx. This repo is for a Go library, not Rust.

**Comment by zigaai** [comment]
oops, i'm sorry
